version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=my_store
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=1234
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data